"""Common-vocabulary coverage study tests (small synthetic fixtures, no network)."""

from __future__ import annotations

import gzip
import importlib
import json
from pathlib import Path

import pytest

pilot = importlib.import_module("scripts.import.pilot_coverage")
common = importlib.import_module("scripts.import.common_coverage")


def _write_jsonl(path: Path, records: list[dict], *, gz: bool = True) -> None:
    text = "\n".join(json.dumps(r, ensure_ascii=False) for r in records) + "\n"
    if gz:
        with gzip.open(path, "wt", encoding="utf-8") as handle:
            handle.write(text)
    else:
        path.write_text(text, encoding="utf-8")


def _house() -> dict:
    return {
        "word": "house",
        "pos": "noun",
        "lang_code": "en",
        "senses": [
            {
                "sense_index": 0,
                "glosses": ["A building for people to live in."],
                "translations": [{"code": "de", "word": "Haus", "tags": ["neuter"]}],
            }
        ],
        "forms": [{"form": "houses", "tags": ["plural"]}],
    }


def _car() -> dict:
    return {
        "word": "car",
        "pos": "noun",
        "lang_code": "en",
        "senses": [
            {
                "sense_index": 0,
                "glosses": ["a vehicle"],
                "translations": [{"code": "de", "word": "Auto"}, {"code": "de", "word": "Wagen"}],
            }
        ],
    }


def _seldom() -> dict:
    return {
        "word": "seldom",
        "pos": "adv",
        "lang_code": "en",
        "senses": [{"sense_index": 0, "glosses": ["rarely"]}],
    }


def _purple() -> dict:
    return {
        "word": "purple",
        "pos": "adj",
        "lang_code": "en",
        "senses": [{"sense_index": 0, "glosses": ["violet in colour"]}],
    }


def _go() -> dict:
    return {
        "word": "go",
        "pos": "verb",
        "lang_code": "en",
        "senses": [{"sense_index": 0, "glosses": ["to move"]}],
        "forms": [{"form": "went", "tags": ["past"]}, {"form": "gone", "tags": ["participle"]}],
    }


def _bank(etym: int, *, with_de: bool) -> dict:
    sense = {"sense_index": 0, "glosses": ["bank"]}
    if with_de:
        sense["translations"] = [{"code": "de", "word": "Bank"}]
    return {
        "word": "bank",
        "pos": "noun",
        "lang_code": "en",
        "etymology_number": etym,
        "senses": [sense],
    }


def _de_record() -> dict:
    return {
        "word": "Haus",
        "pos": "noun",
        "lang_code": "de",
        "tags": ["neuter"],
        "senses": [{"glosses": ["Gebäude"]}],
        "forms": [{"form": "Häuser", "tags": ["nominative", "plural"]}],
    }


def _fd_tei(entries: list[tuple[str, str, str]]) -> str:
    body = "".join(
        f'<entry xml:id="{word}.1"><form><orth>{word}</orth></form><sense>'
        f'<cit type="trans"><quote xml:lang="de">{de}</quote>'
        f"<gramGrp><gen>{gen}</gen></gramGrp></cit></sense></entry>"
        for word, de, gen in entries
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<TEI xmlns="http://www.tei-c.org/ns/1.0"><text><body>'
        f"{body}</body></text></TEI>\n"
    )


def _lemmas_file(path: Path, lines: list[str]) -> None:
    text = (
        "# generated by scripts.import.generate_common_lemma_list (procedure 1.0)\n"
        "# frame: Wiktionary:Frequency lists/TV/2006 (top 2000); licence CC BY-SA 4.0\n"
    )
    text += "\n".join(lines) + "\n"
    path.write_text(text, encoding="utf-8")


def test_read_lemma_list_with_comments_and_categories(tmp_path: Path) -> None:
    path = tmp_path / "lemmas.tsv"
    path.write_text(
        "# source: test\n"
        "house\tnoun\n"
        "go\tverb\n"
        "seldom\n"
        "about\t\trank:9\n"
        "  spaced\tadv  \n"
        "\n",
        encoding="utf-8",
    )
    entries, header = common.read_lemma_list(path)
    assert header == ["source: test"]
    assert entries == [
        {"word": "house", "category": "noun"},
        {"word": "go", "category": "verb"},
        {"word": "seldom", "category": None},
        {"word": "about", "category": None, "rank": "9"},
        {"word": "spaced", "category": "adv"},
    ]


def test_read_lemma_list_rejects_unknown_field(tmp_path: Path) -> None:
    path = tmp_path / "lemmas.tsv"
    path.write_text("x\tbogus\n", encoding="utf-8")
    with pytest.raises(ValueError, match="unknown field"):
        common.read_lemma_list(path)


def test_derive_category() -> None:
    assert common.derive_category("noun") == "noun"
    assert common.derive_category("verb") == "verb"
    assert common.derive_category("adj") == "adj"
    assert common.derive_category("adv") == "adv"
    assert common.derive_category("prep") == "function"
    assert common.derive_category("determiner") == "function"
    assert common.derive_category("name") == "other"
    assert common.derive_category("") == "other"


def test_scan_en_keeps_homonyms_separate_and_detects_form_uses(tmp_path: Path) -> None:
    en = tmp_path / "en.jsonl.gz"
    _write_jsonl(en, [_bank(1, with_de=True), _bank(2, with_de=False), _go()])
    lemmas = [
        {"word": "bank", "category": "noun"},
        {"word": "went", "category": "verb"},
    ]
    scan = pilot.Scan()
    lemma_records, form_uses = common.scan_en_lemma_records(en, lemmas, scan)
    assert len(lemma_records["bank"]) == 2  # both etymologies survive, never merged
    assert sorted(k for k, _ in lemma_records["bank"]) == [
        "bank\tnoun\t1",
        "bank\tnoun\t2",
    ]
    assert lemma_records["went"] == []
    assert form_uses["went"] == ["go\tverb\t0"]


def test_analyze_lemma_aggregates_distinct_de_not_merge_homonyms() -> None:
    errors: list[dict] = []
    lemma = common.analyze_lemma(
        {"word": "bank", "category": "noun"},
        [(pilot.record_key(_bank(1, with_de=True)), _bank(1, with_de=True)),
         (pilot.record_key(_bank(2, with_de=False)), _bank(2, with_de=False))],
        errors,
    )
    assert lemma["present"] is True
    assert lemma["records_matched"] == 2
    assert lemma["has_de"] is True
    assert lemma["de_words"] == ["bank"]  # casefolded by analyze_entry
    assert lemma["distinct_de_count"] == 1
    assert lemma["pos_observed"] == ["noun"]
    assert lemma["category"] == "noun"
    assert lemma["category_source"] == "list"
    assert len(lemma["records"]) == 2
    assert {r["identity"] for r in lemma["records"]} == {
        "bank\tnoun\t1",
        "bank\tnoun\t2",
    }


def test_analyze_lemma_derived_category_and_verb_type() -> None:
    errors: list[dict] = []
    lemma = common.analyze_lemma(
        {"word": "go", "category": None},
        [(pilot.record_key(_go()), _go())],
        errors,
    )
    assert lemma["category"] == "verb"
    assert lemma["category_source"] == "derived"
    assert lemma["verb_type"] == "conjugated"


def test_attach_de_enrichment() -> None:
    lemma = {"word": "house", "de_words": ["haus"], "de_words_total": 0}
    de_index = {
        "haus": {
            "word": "Haus",
            "gender_tags": ["neuter"],
            "form_count": 2,
            "has_gloss": True,
        }
    }
    common.attach_de_enrichment(lemma, de_index)
    assert lemma["de_matched"] == 1
    assert lemma["de_gender_labels"] == 1
    assert lemma["de_with_forms"] == 1
    assert lemma["de_with_gloss"] == 1


def test_attach_freedict_exclusive_buckets() -> None:
    fd_index = {
        "house": [{"text": "Haus", "gen": "neut"}],
        "purple": [{"text": "lila", "gen": None}],
    }
    house = {"norm_word": "house", "has_de": True, "fd_de_count": 0}
    car = {"norm_word": "car", "has_de": True, "fd_de_count": 0}
    purple = {"norm_word": "purple", "has_de": False, "fd_de_count": 0}
    seldom = {"norm_word": "seldom", "has_de": False, "fd_de_count": 0}
    expected = [
        (house, "both"),
        (car, "en_only"),
        (purple, "freedict_only"),
        (seldom, "neither"),
    ]
    for lemma, bucket in expected:
        common.attach_freedict(lemma, fd_index)
        assert lemma["exclusive"] == bucket
    assert house["fd_de_count"] == 1
    assert house["fd_genders"] == 1


def test_lemma_metrics_na_when_empty() -> None:
    assert common.lemma_metrics([])["lemmas_scored"]["status"] == "N/A"


def test_end_to_end_main(tmp_path: Path) -> None:
    en = tmp_path / "en.jsonl.gz"
    de = tmp_path / "de.jsonl.gz"
    freedict = tmp_path / "fd.tei"
    lemmas = tmp_path / "lemmas.tsv"
    report = tmp_path / "common-words-coverage.json"
    _write_jsonl(
        en,
        [_house(), _car(), _seldom(), _purple(), _go()],
    )
    _write_jsonl(de, [_de_record()])
    freedict.write_text(
        _fd_tei([("house", "Haus", "neut"), ("purple", "lila", "m")]),
        encoding="utf-8",
    )
    _lemmas_file(
        lemmas,
        [
            "house\tnoun",
            "car\tnoun",
            "seldom\tadv",
            "purple\tadj",
            "went\tverb",
            "zzz\tnoun",
        ],
    )
    argv = [
        "--en", str(en),
        "--de", str(de),
        "--freedict", str(freedict),
        "--lemmas", str(lemmas),
        "--report", str(report),
    ]
    assert common.main(argv) == 0
    payload = json.loads(report.read_text(encoding="utf-8"))

    assert payload["metrics"]["all"]["lemmas_scored"]["status"] == "MEASURED"
    counts = payload["counts"]
    assert counts["lemmas_requested"] == 6
    assert counts["lemmas_unique"] == 6
    assert counts["lemmas_with_records"] == 4
    assert counts["lemmas_missing_from_en"] == 2  # "went" (inflected-only) and "zzz"
    assert counts["lemmas_inflected_only_nonheadword"] == 1  # "went" is a form of "go"

    all_metrics = payload["metrics"]["all"]
    # among the 6 lemmas, house+car carry German from en.wiktionary
    assert all_metrics["en_de_coverage"]["numerator"] == 2
    assert all_metrics["en_de_coverage"]["denominator"] == 6
    # purple has no en German but has FreeDict; house has en German + FreeDict
    assert all_metrics["freedict_de_coverage"]["numerator"] == 2
    assert all_metrics["any_source_de_coverage"]["numerator"] == 3  # house, car, purple

    noun_metrics = payload["metrics"]["per_category"]["noun"]["en_de_coverage"]
    assert noun_metrics["numerator"] == 2
    assert noun_metrics["denominator"] == 3  # house, car, zzz (missing) carry the noun tag

    assert payload["exclusive_contribution"]["counts"] == {
        "en_only": 1,       # car
        "freedict_only": 1,  # purple
        "both": 1,           # house
        "neither": 3,        # seldom, went, zzz
    }
    assert payload["freedict"]["status"] == "MEASURED"
    assert payload["de_enrichment"]["matched"] == 1  # Haus
    assert payload["scans"]["en"]["parse_errors"] == 0
    assert payload["recommendation"]["production_import"] == "NO_GO"
    assert payload["recommendation"]["remaining_blockers"] == ["L1", "L3", "L4"]
    assert payload["licences"]["freedict_eng_deu"].startswith("VERIFIED")
    assert payload["inputs"]["lemmas"]["header"][0].startswith("generated by")