"""initial schema

Revision ID: 4ba08e47a971
Revises: 
Create Date: 2026-10-08 14:42:18.931732

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '4ba08e47a971'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_sentences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lemma', sa.String(length=255), nullable=False),
    sa.Column('normalized_lemma', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('part_of_speech', sa.String(length=32), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('register', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lexemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lexemes_normalized_lemma'), ['normalized_lemma'], unique=False)

    op.create_table('lexical_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_lexeme_id', sa.String(length=36), nullable=False),
    sa.Column('target_lexeme_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_lexeme_id', 'target_lexeme_id', 'relation_type', name='uq_lexical_relation')
    )
    with op.batch_alter_table('lexical_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lexical_relations_source_lexeme_id'), ['source_lexeme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lexical_relations_target_lexeme_id'), ['target_lexeme_id'], unique=False)

    op.create_table('senses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lexeme_id', sa.String(length=36), nullable=False),
    sa.Column('sense_index', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('register', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme_id', 'sense_index', name='uq_sense_index')
    )
    with op.batch_alter_table('senses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senses_lexeme_id'), ['lexeme_id'], unique=False)

    op.create_table('word_forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lexeme_id', sa.String(length=36), nullable=False),
    sa.Column('surface', sa.String(length=255), nullable=False),
    sa.Column('normalized_surface', sa.String(length=255), nullable=False),
    sa.Column('form_type', sa.String(length=32), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme_id', 'surface', name='uq_wordform_surface')
    )
    with op.batch_alter_table('word_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_forms_lexeme_id'), ['lexeme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_forms_normalized_surface'), ['normalized_surface'], unique=False)

    op.create_table('example_words',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('example_sentence_id', sa.String(length=36), nullable=False),
    sa.Column('word_form_id', sa.String(length=36), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['example_sentence_id'], ['example_sentences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_form_id'], ['word_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('example_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_example_words_example_sentence_id'), ['example_sentence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_example_words_word_form_id'), ['word_form_id'], unique=False)

    op.create_table('frequencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lexeme_id', sa.String(length=36), nullable=False),
    sa.Column('word_form_id', sa.String(length=36), nullable=True),
    sa.Column('corpus', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_form_id'], ['word_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corpus', 'lexeme_id', 'word_form_id', name='uq_frequency_corpus')
    )
    with op.batch_alter_table('frequencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frequencies_lexeme_id'), ['lexeme_id'], unique=False)

    op.create_table('lookups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('normalized_surface', sa.String(length=255), nullable=False),
    sa.Column('lexeme_id', sa.String(length=36), nullable=False),
    sa.Column('word_form_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_form_id'], ['word_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_surface', 'word_form_id', name='uq_lookup_surface_form')
    )
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.create_index('ix_lookups_normalized_surface', ['normalized_surface'], unique=False)

    op.create_table('morphological_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('word_form_id', sa.String(length=36), nullable=False),
    sa.Column('case', sa.String(length=16), nullable=True),
    sa.Column('number', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('person', sa.String(length=8), nullable=True),
    sa.Column('tense', sa.String(length=16), nullable=True),
    sa.Column('mood', sa.String(length=16), nullable=True),
    sa.Column('degree', sa.String(length=16), nullable=True),
    sa.Column('voice', sa.String(length=16), nullable=True),
    sa.Column('verb_form', sa.String(length=16), nullable=True),
    sa.Column('adjective_form', sa.String(length=32), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['word_form_id'], ['word_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_form_id')
    )
    # PostgreSQL-only search infrastructure: German full-text search for
    # the definition stage (pg_trgm provides similarity() for the fuzzy
    # stage; the extension must exist for it).
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
        op.create_index(
            'ix_senses_definition_fts',
            'senses',
            [sa.func.to_tsvector('german', sa.text('definition'))],
            postgresql_using='gin',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.drop_index('ix_senses_definition_fts', table_name='senses')
    op.drop_table('morphological_features')
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.drop_index('ix_lookups_normalized_surface')

    op.drop_table('lookups')
    with op.batch_alter_table('frequencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frequencies_lexeme_id'))

    op.drop_table('frequencies')
    with op.batch_alter_table('example_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_example_words_word_form_id'))
        batch_op.drop_index(batch_op.f('ix_example_words_example_sentence_id'))

    op.drop_table('example_words')
    with op.batch_alter_table('word_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_forms_normalized_surface'))
        batch_op.drop_index(batch_op.f('ix_word_forms_lexeme_id'))

    op.drop_table('word_forms')
    with op.batch_alter_table('senses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senses_lexeme_id'))

    op.drop_table('senses')
    with op.batch_alter_table('lexical_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lexical_relations_target_lexeme_id'))
        batch_op.drop_index(batch_op.f('ix_lexical_relations_source_lexeme_id'))

    op.drop_table('lexical_relations')
    with op.batch_alter_table('lexemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lexemes_normalized_lemma'))

    op.drop_table('lexemes')
    op.drop_table('example_sentences')
    # ### end Alembic commands ###
